name: lesspass
version: "0.1.0"
summary: lesspass cli
description: lesspass cli
confinement: strict

apps:
  lesspass:
    command: lesspass

parts:
  lesspass:
    plugin: nodejs
    node-packages:
      - lesspass-cli
